name: 'Terraform Init and Apply'

on:
  workflow_call:
    inputs:
      directory:
        description: "Working directory name"
        type: string
        required: true

      environment:
        description: "Target Environment"
        type: string
        required: true
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_AZUREAD: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TF_VAR_proj_env: ${{ inputs.environment }}
  TF_VAR_tag_environment: ${{ inputs.environment }}
  TF_VAR_tag_repository: ${{ github.event.repository.name }}
  TF_VAR_github_repository_owner: ${{ github.repository_owner }}
  TF_VAR_github_repository_name: ${{ github.event.repository.name }}
  TF_VAR_github_environment_name: ""

jobs:
  approval:
    name: 'Approval'
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment: approval
    steps:
      - name: Approval Step
        run: echo "${{ github.event.review.state }}"

  init-and-apply: 
    name: 'Apply'
    runs-on: ubuntu-latest
    needs: approval
    if: ${{ github.ref_name == 'main' && needs.approval.result == 'success' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate input directory
        run: |
          if [ -d ${{ inputs.directory }} ]; then
            echo "Directory exists"
          else 
            echo "Directory does not exist."
            exit 1
          fi

      - name: Set Github URL
        run: git config --global url."https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf https://github.com

      - name: Azure CLI Login (Service Principal)
        run: |
          az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
          az account set --subscription "$AZURE_SUBSCRIPTION_ID"
      
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ inputs.directory }}

      - name: Terraform Apply        
        run: terraform apply -var-file="terraform.tfvars" -auto-approve
        working-directory: ${{ inputs.directory }}